### ISSUE TITLE
Reconciliation  doesn't continue when error appears

### ISSUE THREAD

**Issue by dafe-corporate-sap** [SAP/sap-btp-service-operator#353]
We are creating tow services identity and sms.
sms depends on identity via field called iasServiceInstanceName. More info [here](https://wiki.one.int.sap/wiki/display/SMEB1/Subscription+of+SMS)

We are creating both serviceinstances via helm chart. It means they are created at the same time. 
Previously we use btp-service-operator version 0.3.3 and there was no problem.
Then we have upgraded btp-service-operator to version 0.5.3.

And now we are getting error:
![image](https://github.com/SAP/sap-btp-service-operator/assets/101183869/7b0aeac9-86df-471e-8bc0-1e54d0b8b3bd)

It means the sms instance expects identity to be ready. But since both object are created at the same time sms reports an error.

If I force reconciliation on the sms service (by changing spec back and force) the instance gets reconciled:
![image](https://github.com/SAP/sap-btp-service-operator/assets/101183869/b96069df-4f0e-4e10-8b50-233ba6d14d55)

Can you please check if it is regression?

**Comment by kerenlahav** [comment]
This was actually a bug fix since there were brokers who complained their service was flooded with the same invalid request over and over again (for example when the user passed an invalid parameter there is no point in sending this request again since it will always fail).
I understand your use case is valid for a retry and we are currently examining possible solutions.

**Comment by kerenlahav** [comment]
Hi @dafe-corporate-sap
A solution for this issue is available in release v0.5.7 
for such cases we added a dedicated annotation - "services.cloud.sap.com/ignoreNonTransientError", add it with the value "true" to the instance that fails with non transient error and should be retried.
adding this annotation will cause the operator to ignore non transient errors and keep trying until one of two conditions is met:
1. request succeeds
2. timeout (2 hours since the annotation was added)
the operator will remove this annotation once not relevant anymore.
please update if it solves your issue.

**Comment by kerenlahav** [comment]
reopen if not resolved

**Comment by dafe-corporate-sap** [comment]
Hi,

we are managing our deployments with gitops.
The state is committed in github repository.
In this case state would also contain  annotation "services.cloud.sap.com/ignoreNonTransientError" with the value "true".
If btp-service-operator removes this annotation than our gitops component (flux) will recreate it.
This will lead to endless loop of object changes.

Other than that, this behavior is completely against the Kubernetes operator pattern. Of course, the operator should slow down with some backoff, but never give up. in case of errors.

In case of really longer lasting errors, the behavior is bad, because
-	it breaks any self-healing and eventual consistency
-	it requires manual effort from humans, to re-trigger reconciliation.

Please reconsider the solution.

Best regards
Daniel.

**Comment by JohannesRu** [comment]
we are also highly affecrted by this reconcilation situation. K8 is all about self-healing and a functioning reconcilation loop. Can we meet and have a shared look at the problem. Maybe I am handling it wrong from my side?

**Comment by kerenlahav** [comment]
Hi @JohannesRu 
We are currently working on a solution that will balance between the load on service brokers and k8s self-healing.
The original issue was that brokers complained about receiving the same request over and over again although the response was "400 - bad request".
In most cases 400 response means the request is invalid and some parameter needs to be changed so there is no point of sending it again until spec is changed, but as we found out later there are some cases that 400 response is temporary (for example when an instance is dependent on another instance). 
since we cannot tell when 400 response is final or not, we will give a "grace period" for such errors, the operator will keep retrying for 24 hours (according to the controller backoff), if the request will fail after 24 hours it will be marked as non transient and won't be sent again until spec is changed.
Will this solution solve your issue? if not please elaborate on your use case

**Comment by cbarbian-sap** [comment]
This is definitely better than the current behaviour, as it will allow things to become consistent, at least if it happens within 24 hours. But still, I do not understand why you complicate things that much at all. I would expect that
a) BTP backends are resilient enough to survive/block any (home-made or really malicious) DDOS-like situations (with something like 429 - Too many requests)
b) it will be enough if clients behave politely by implementing decent backoffs. What is the issue if the BTP service operator would just retry forever (with a final frequency of once per 10m or once per hour)? This would not kill BTP backend, would it?

**Comment by pre** [comment]
The problem reports from BTP service broker people might be related to the cases where sap-btp-service-operator fails to throttle it's retries and floods the service broker. I have witnessed such cases, for example in https://github.com/SAP/sap-btp-service-operator/issues/190 

In the flood cases witnessed by myself, sap-btp-service-operator retries  ~10-50 times *per second* without throttling - until I have manually terminated that Pod of sap-btp-service-operator. After restarting in a new Pod, sap-btp-service-operator has retried again gracefully (not flooding).

**Comment by sdischer-sap** [comment]
Got to agree with the points being made already:
Provided that there is a proper backoff taking effect the operator should not be responsible for blocking http requests entirely despite the results of previous attempts. It would prevent any self healing which is kind of the biggest selling point of using k8s operators in the first place. 

If brokers want to manually address failing http requests they should probably reach out to the users sending those requests, since they are the only wants being able to fix them for good.

**Comment by kerenlahav** [comment]
I agree, when brokers complained the backoff base delay was 1 second, that caused a large amount of requests in a short period of time.  For a long time now, the backoff delay base is 10 seconds so i think we can give it another try.
Removing the 24 hours limit for now, failed requests will be sent forever, max backoff delay is 3 hours, meaning that eventaully a failed request will be sent once in every 3 hours which the broker should be fine with.

**Comment by kerenlahav** [comment]
fixed in https://github.com/SAP/sap-btp-service-operator/releases/tag/v0.6.0

**Comment by ankitamohanty7** [comment]
We are still facing this issue, reconciliation doesnt retry creation of ServiceInstance after error is fixed
Entitlement was not present for initial few minutes due to which SI creation failed, but even after entitlement provisioning succeeded, the SI was not created

Entitlement provisionined after an initial delay

<img width="965" alt="Image" src="https://github.com/user-attachments/assets/530e3b7f-326e-47fd-a37e-a2a0d794e8cd" />

ServiceInstance not created even though recon was prbably retried after 3 hours. Timestamp included in screenshot

<img width="1284" alt="Image" src="https://github.com/user-attachments/assets/c7c92785-1762-4732-95e3-f41d03f3648b" />

As per @kerenlahav , after 3 hours SI should provision if error is not there, but doesnt seem to be happening

Hence reopening this issue

**Comment by kerenlahav** [comment]
this issue is **more that a year old**, did you verify it back than? did iit work? what changed?
